baseurl: "http://carolinarscm.org"
languageCode: "en-us"
title: "RSCM Carolina Course for Girls & Adults"
description: Psallam spiritu et mente
MetaDataFormat: "yaml"
copyright: "Copyright &#xA9; 2015 RSCM Carolina Course for Girls &amp; Adults"

params:
  googlesite: carolinarscm.org

  dateline: The 2015 course dates are July 13th through July 19th.
  current: 2015

  # Max number of new articles to show on main page
  maxnews: 6

menu:
  main:
    - name: About
      weight: 100
    - name: Contact Us
      weight: 100
      url: /contact
    - name: Past Courses
      weight: 100
    - name: Directors and Organists
      parent: Past Courses
      weight: -50
      url: /courses/

  links:
    - name: Central North Carolina Chapter of the American Guild of Organists
      url: http://www.agohq.org/chapters/centralnc/
    - name: John-Paul Buzard Pipe Organ Builders
      url: http://buzardorgans.com/
    - name: Katie Dickson Photography
      url: http://www.katiedickson.com/
    - name: Charlotte Training Course for Boys, Girls, Teens, and Adults
      url: http://www.saintjohns-charlotte.org/rscm/
    - name: RSCM America
      url: http://www.rscmamerica.org
    - name: RSCM International
      url: http://www.rscm.com
