baseurl: "http://carolinarscm.org"
languageCode: "en-us"
title: "RSCM Carolina Course for Girls & Adults"
description: Psallam spiritu et mente
MetaDataFormat: "yaml"
copyright: "Copyright &#xA9; 2020 RSCM Carolina Course for Girls &amp; Adults"

params:
  googlesite: carolinarscm.org

  dateline: 2021 Course dates are July 12th - 18th at Duke University.
  current: 2021

  # Max number of new articles to show on main page
  maxnews: 4

menu:
  main:
    - name: About
      weight: 100
    - name: Contact Us
      weight: 100
      url: /contact
    - name: Past Courses
      weight: 100
    - name: Register
      weight: 1
      url: /register
    - name: Directors and Organists
      parent: Past Courses
      weight: -50
      url: /courses/
#    - name: Maps
#      weight: 140
#      url: https://www.google.com/maps/d/edit?mid=1tjUeaZAe8CGTJLLZrpjJE99mNUU
#    - name: Course Feedback Survey
#      weight: 150
#      url: https://docs.google.com/forms/d/e/1FAIpQLSdYrjlZflw3DwILMsE5GejcvKjrTRP4Su7sQ6di7n_C70zGlw/viewform

  links:
    - name: Central North Carolina Chapter of the American Guild of Organists
      url: http://www.agohq.org/chapters/centralnc/
    - name: John-Paul Buzard Pipe Organ Builders
      url: http://buzardorgans.com/
    - name: Katie Dickson Photography
      url: http://www.katiedickson.com/
    - name: Charlotte Training Course for Boys, Girls, Teens, and Adults
      url: http://www.saintjohns-charlotte.org/rscm/
    - name: RSCM America
      url: http://www.rscmamerica.org
    - name: RSCM International
      url: http://www.rscm.com
