baseurl: "http://carolinarscm.org"
languageCode: "en-us"
title: "RSCM Carolina Course for Girls & Adults"
description: Psallam spiritu et mente
MetaDataFormat: "yaml"
copyright: "Copyright &#xA9; 2016 RSCM Carolina Course for Girls &amp; Adults"

params:
  googlesite: carolinarscm.org

  dateline: The 2016 course dates are June 27th through July 3rd.
  current: 2016

  # Max number of new articles to show on main page
  maxnews: 5

menu:
  main:
    - name: About
      weight: 100
    - name: Contact Us
      weight: 100
      url: /contact
    - name: Past Courses
      weight: 100
    - name: Register
      weight: 1
      url: /register
    - name: Directors and Organists
      parent: Past Courses
      weight: -50
      url: /courses/
#    - name: Maps
#      weight: 140
#      url: https://www.google.com/maps/d/edit?mid=zF-x4rG4Mzvs.kMBQPQlL_wOk
#    - name: Course Feedback Survey
#      weight: 150
#      url: http://goo.gl/forms/yEcGPLXIoE

  links:
    - name: Central North Carolina Chapter of the American Guild of Organists
      url: http://www.agohq.org/chapters/centralnc/
    - name: John-Paul Buzard Pipe Organ Builders
      url: http://buzardorgans.com/
    - name: Katie Dickson Photography
      url: http://www.katiedickson.com/
    - name: Charlotte Training Course for Boys, Girls, Teens, and Adults
      url: http://www.saintjohns-charlotte.org/rscm/
    - name: RSCM America
      url: http://www.rscmamerica.org
    - name: RSCM International
      url: http://www.rscm.com
